version: '3'

# Task automatically loads .env file if present
dotenv: ['.env']

# Environment variables used:
# - DATABASE_URL: PostgreSQL connection string (backend)
# - PORT: Backend HTTP port (default 8080)
# - JWT_SECRET: JWT signing secret (backend)
# - CORS_ALLOWED_ORIGINS: Comma-separated allowed origins (backend)
# - NEXT_PUBLIC_API_URL: Backend API URL for frontend (e.g., http://localhost:8080)

vars:
  PORT: '{{.PORT | default "8080"}}'
  NEXT_PUBLIC_API_URL: '{{.NEXT_PUBLIC_API_URL | default "http://localhost:8080"}}'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ============================================
  # DEVELOPMENT
  # ============================================
  dev:
    desc: Start development environment (installs deps, runs backend + frontend)
    cmds:
      - task: deps
      - task: db:check
      - task: dev:run

  dev:run:
    desc: Run backend and frontend in parallel
    deps: [dev:backend, dev:frontend]

  dev:backend:
    desc: Start backend in development mode
    dir: backend
    cmds:
      - echo "Starting backend on port {{.PORT}}..."
      - go run cmd/server/main.go

  dev:frontend:
    desc: Start frontend in development mode
    dir: frontend
    env:
      NEXT_PUBLIC_API_URL: '{{.NEXT_PUBLIC_API_URL}}'
    cmds:
      - echo "Starting frontend on port 3000..."
      - echo "API URL {{.NEXT_PUBLIC_API_URL}}"
      - pnpm dev

  # ============================================
  # PRODUCTION
  # ============================================
  prod:
    desc: Start production environment (installs deps, builds, runs backend + frontend)
    cmds:
      - task: deps
      - task: db:check
      - task: prod:run

  prod:run:
    desc: Run backend and frontend in parallel (production)
    deps: [prod:backend, prod:frontend]

  prod:backend:
    desc: Build and run backend in production mode
    dir: backend
    cmds:
      - echo "Building backend..."
      - go build -o bin/server.exe cmd/server/main.go
      - echo "Starting backend on port {{.PORT}}..."
      - bin/server.exe

  prod:frontend:
    desc: Build and run frontend in production mode
    dir: frontend
    env:
      NEXT_PUBLIC_API_URL: '{{.NEXT_PUBLIC_API_URL}}'
    cmds:
      - echo "Building frontend with API URL {{.NEXT_PUBLIC_API_URL}}..."
      - pnpm build
      - echo "Starting frontend in production mode..."
      - pnpm start

  # ============================================
  # DEPENDENCY MANAGEMENT
  # ============================================
  deps:
    desc: Install all dependencies (backend, frontend, agent)
    cmds:
      - task: deps:backend
      - task: deps:frontend
      - task: deps:agent

  deps:backend:
    desc: Install backend Go dependencies
    dir: backend
    cmds:
      - echo "Installing backend dependencies..."
      - go mod download
      - go mod tidy
    status:
      - test -f go.sum

  deps:frontend:
    desc: Install frontend Node dependencies
    dir: frontend
    cmds:
      - echo "Installing frontend dependencies..."
      - pnpm install --frozen-lockfile
    status:
      - test -d node_modules

  deps:agent:
    desc: Install agent Go dependencies
    dir: agent
    cmds:
      - echo "Installing agent dependencies..."
      - go mod download
      - go mod tidy
    status:
      - test -f go.sum

  # ============================================
  # SETUP (alias for deps, for backwards compatibility)
  # ============================================
  setup:
    desc: Initial setup - install all dependencies
    cmds:
      - task: deps

  setup:backend:
    desc: Install backend dependencies (alias)
    cmds:
      - task: deps:backend

  setup:frontend:
    desc: Install frontend dependencies (alias)
    cmds:
      - task: deps:frontend

  setup:agent:
    desc: Install agent dependencies (alias)
    cmds:
      - task: deps:agent

  # ============================================
  # DATABASE
  # ============================================
  db:check:
    desc: Check database connection
    dir: backend
    cmds:
      - go run cmd/dbcheck/main.go

  db:migrate:
    desc: Run database migrations
    dir: backend
    cmds:
      - task: db:check
      - echo "Running migrations..."
      - go run cmd/server/main.go

  # ============================================
  # BUILD
  # ============================================
  build:
    desc: Build all components (backend, frontend, agent)
    cmds:
      - task: deps
      - task: build:backend
      - task: build:frontend
      - task: build:agent

  build:backend:
    desc: Build backend binary
    dir: backend
    cmds:
      - echo "Building backend..."
      - go build -o bin/server.exe cmd/server/main.go
      - echo "Backend built at backend/bin/server.exe"

  build:frontend:
    desc: Build frontend for production
    dir: frontend
    env:
      NEXT_PUBLIC_API_URL: '{{.NEXT_PUBLIC_API_URL}}'
    cmds:
      - echo "Building frontend with API URL {{.NEXT_PUBLIC_API_URL}}..."
      - pnpm build
      - echo "Frontend built successfully"

  build:agent:
    desc: Build agent binary for Linux
    dir: agent
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - echo "Building agent for Linux..."
      - go build -o bin/configuratix-agent ./cmd/agent
      - echo "Agent built at agent/bin/configuratix-agent"

  build:agent:windows:
    desc: Build agent binary for Windows (for testing)
    dir: agent
    cmds:
      - echo "Building agent for Windows..."
      - go build -o bin/configuratix-agent.exe ./cmd/agent
      - echo "Agent built at agent/bin/configuratix-agent.exe"

  # ============================================
  # DEPLOY AGENT
  # ============================================
  deploy:agent:
    desc: Build and copy agent to a remote server
    dir: agent
    cmds:
      - task: build:agent
      - echo "Agent binary ready at agent/bin/configuratix-agent"
      - 'echo "Copy to server with: scp agent/bin/configuratix-agent user@server:/usr/local/bin/"'

  agent:publish:
    desc: Build agent and publish to backend for auto-updates
    vars:
      AGENT_VERSION: '{{.AGENT_VERSION | default "0.1.0"}}'
    cmds:
      - task: build:agent
      - echo "Publishing agent version {{.AGENT_VERSION}} to backend..."
      - powershell -Command "New-Item -ItemType Directory -Force -Path backend/agent-binaries | Out-Null"
      - powershell -Command "Copy-Item agent/bin/configuratix-agent backend/agent-binaries/configuratix-agent"
      - |
        powershell -Command "
          $$hash = (Get-FileHash -Algorithm SHA256 backend/agent-binaries/configuratix-agent).Hash.ToLower()
          $$size = (Get-Item backend/agent-binaries/configuratix-agent).Length
          $$json = @{
            version = '{{.AGENT_VERSION}}'
            checksum = $$hash
            size = $$size
            updated_at = (Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ')
          } | ConvertTo-Json
          $$json | Out-File -FilePath backend/agent-binaries/version.json -Encoding UTF8
          Write-Host 'Published agent version {{.AGENT_VERSION}}'
          Write-Host \"Checksum: $$hash\"
          Write-Host \"Size: $$size bytes\"
        "

  # ============================================
  # CLEAN
  # ============================================
  clean:
    desc: Clean build artifacts
    cmds:
      - powershell -Command "Remove-Item -Recurse -Force -ErrorAction SilentlyContinue backend\bin, frontend\.next, frontend\dist, agent\bin"
      - echo "Clean complete"

  clean:all:
    desc: Clean build artifacts and node_modules
    cmds:
      - task: clean
      - powershell -Command "Remove-Item -Recurse -Force -ErrorAction SilentlyContinue frontend\node_modules"
      - echo "Full clean complete"
